//go:build go1.22

// Package dataapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package dataapi

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for DataServiceHealthService.
const (
	CsInvEditData DataServiceHealthService = "cs-inv-edit-data"
)

// Valid indicates whether the value is a known member of the DataServiceHealthService enum.
func (e DataServiceHealthService) Valid() bool {
	switch e {
	case CsInvEditData:
		return true
	default:
		return false
	}
}

// Defines values for DataServiceHealthStatus.
const (
	Ok DataServiceHealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the DataServiceHealthStatus enum.
func (e DataServiceHealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for PriceResultCacheState.
const (
	Fresh PriceResultCacheState = "fresh"
	Stale PriceResultCacheState = "stale"
)

// Valid indicates whether the value is a known member of the PriceResultCacheState enum.
func (e PriceResultCacheState) Valid() bool {
	switch e {
	case Fresh:
		return true
	case Stale:
		return true
	default:
		return false
	}
}

// DataServiceHealth defines model for DataServiceHealth.
type DataServiceHealth struct {
	Service DataServiceHealthService `json:"service"`
	Status  DataServiceHealthStatus  `json:"status"`
	Time    time.Time                `json:"time"`
	Version string                   `json:"version"`
}

// DataServiceHealthService defines model for DataServiceHealth.Service.
type DataServiceHealthService string

// DataServiceHealthStatus defines model for DataServiceHealth.Status.
type DataServiceHealthStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// PriceHistoryResult defines model for PriceHistoryResult.
type PriceHistoryResult struct {
	AppId          int          `json:"appId"`
	BaselineSource string       `json:"baselineSource"`
	Currency       string       `json:"currency"`
	MarketName     string       `json:"marketName"`
	Observations   []PriceQuote `json:"observations"`
}

// PriceItemResult defines model for PriceItemResult.
type PriceItemResult struct {
	MarketName string       `json:"marketName"`
	Quotes     []PriceQuote `json:"quotes"`
}

// PriceQuery defines model for PriceQuery.
type PriceQuery struct {
	AppId       *int     `json:"appId,omitempty"`
	Currency    string   `json:"currency"`
	MarketNames []string `json:"marketNames"`
}

// PriceQuote defines model for PriceQuote.
type PriceQuote struct {
	AdjustedAmountMinor  *int      `json:"adjustedAmountMinor,omitempty"`
	AdjustedDisplayPrice *string   `json:"adjustedDisplayPrice,omitempty"`
	AmountMinor          *int      `json:"amountMinor,omitempty"`
	Currency             string    `json:"currency"`
	DisplayPrice         string    `json:"displayPrice"`
	ListingCount         *int      `json:"listingCount,omitempty"`
	MarketName           string    `json:"marketName"`
	ObservedAt           time.Time `json:"observedAt"`
	PriceMultiplier      float32   `json:"priceMultiplier"`
	Source               string    `json:"source"`
	Url                  *string   `json:"url,omitempty"`
}

// PriceResult defines model for PriceResult.
type PriceResult struct {
	BaselineSource *string                `json:"baselineSource,omitempty"`
	CacheState     *PriceResultCacheState `json:"cacheState,omitempty"`
	Currency       string                 `json:"currency"`
	Errors         []ProviderError        `json:"errors"`
	Items          []PriceItemResult      `json:"items"`
	Listings       []PriceQuote           `json:"listings"`
	ScannedAt      time.Time              `json:"scannedAt"`
	ServedAt       *time.Time             `json:"servedAt,omitempty"`
}

// PriceResultCacheState defines model for PriceResult.CacheState.
type PriceResultCacheState string

// PriceSearchItem defines model for PriceSearchItem.
type PriceSearchItem struct {
	ImageUrl   *string `json:"imageUrl,omitempty"`
	MarketName string  `json:"marketName"`
	Name       string  `json:"name"`
}

// PriceSearchResult defines model for PriceSearchResult.
type PriceSearchResult struct {
	Items []PriceSearchItem `json:"items"`
}

// ProviderError defines model for ProviderError.
type ProviderError struct {
	Message string `json:"message"`
	Source  string `json:"source"`
}

// ProviderList defines model for ProviderList.
type ProviderList struct {
	Providers []string `json:"providers"`
}

// GetPriceHistoryParams defines parameters for GetPriceHistory.
type GetPriceHistoryParams struct {
	MarketName string     `form:"marketName" json:"marketName"`
	Currency   string     `form:"currency" json:"currency"`
	AppId      *int       `form:"appId,omitempty" json:"appId,omitempty"`
	Source     *string    `form:"source,omitempty" json:"source,omitempty"`
	From       *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To         *time.Time `form:"to,omitempty" json:"to,omitempty"`
	Limit      *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchPricesParams defines parameters for SearchPrices.
type SearchPricesParams struct {
	Query string `form:"query" json:"query"`
	AppId *int   `form:"appId,omitempty" json:"appId,omitempty"`
	Limit *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// QueryPricesJSONRequestBody defines body for QueryPrices for application/json ContentType.
type QueryPricesJSONRequestBody = PriceQuery

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)

	// (GET /v1/prices/history)
	GetPriceHistory(w http.ResponseWriter, r *http.Request, params GetPriceHistoryParams)

	// (POST /v1/prices/query)
	QueryPrices(w http.ResponseWriter, r *http.Request)

	// (GET /v1/prices/search)
	SearchPrices(w http.ResponseWriter, r *http.Request, params SearchPricesParams)

	// (GET /v1/providers)
	ListProviders(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPriceHistory operation middleware
func (siw *ServerInterfaceWrapper) GetPriceHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPriceHistoryParams

	// ------------- Required query parameter "marketName" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "marketName", r.URL.Query(), &params.MarketName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "marketName"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "marketName", Err: err})
		}
		return
	}

	// ------------- Required query parameter "currency" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "currency", r.URL.Query(), &params.Currency, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "currency"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currency", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "appId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "appId", r.URL.Query(), &params.AppId, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "appId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "appId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPriceHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueryPrices operation middleware
func (siw *ServerInterfaceWrapper) QueryPrices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueryPrices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPrices operation middleware
func (siw *ServerInterfaceWrapper) SearchPrices(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPricesParams

	// ------------- Required query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "appId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "appId", r.URL.Query(), &params.AppId, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "appId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "appId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPrices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProviders operation middleware
func (siw *ServerInterfaceWrapper) ListProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadiness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/providers", wrapper.ListProviders)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/prices/query", wrapper.QueryPrices)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/prices/history", wrapper.GetPriceHistory)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/prices/search", wrapper.SearchPrices)

	return m
}
