// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type DataServiceHealth = {
  status: "ok";
  service: "cs-inv-edit-data";
  version: string;
  time: string;
};

export type ProviderList = {
  providers: Array<string>;
};

export type PriceQuery = {
  marketNames: Array<string>;
  currency: string;
  appId?: number;
};

export type PriceQuote = {
  source: string;
  marketName: string;
  currency: string;
  amountMinor?: number;
  displayPrice: string;
  priceMultiplier: number;
  adjustedAmountMinor?: number;
  adjustedDisplayPrice?: string;
  listingCount?: number;
  url?: string;
  observedAt: string;
};

export type PriceItemResult = {
  marketName: string;
  quotes: Array<PriceQuote>;
};

export type ProviderError = {
  source: string;
  message: string;
};

export type PriceResult = {
  currency: string;
  items: Array<PriceItemResult>;
  listings: Array<PriceQuote>;
  errors: Array<ProviderError>;
  scannedAt: string;
  servedAt?: string;
  cacheState?: "fresh" | "stale";
};

export type ErrorResponse = {
  error: string;
};

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/healthz";
};

export type GetHealthResponses = {
  /**
   * Service health
   */
  200: DataServiceHealth;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetReadinessData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/readyz";
};

export type GetReadinessResponses = {
  /**
   * Service readiness
   */
  200: DataServiceHealth;
};

export type GetReadinessResponse =
  GetReadinessResponses[keyof GetReadinessResponses];

export type ListProvidersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/providers";
};

export type ListProvidersResponses = {
  /**
   * Available price providers
   */
  200: ProviderList;
};

export type ListProvidersResponse =
  ListProvidersResponses[keyof ListProvidersResponses];

export type QueryPricesData = {
  body: PriceQuery;
  path?: never;
  query?: never;
  url: "/v1/prices/query";
};

export type QueryPricesErrors = {
  /**
   * Invalid query
   */
  400: ErrorResponse;
};

export type QueryPricesError = QueryPricesErrors[keyof QueryPricesErrors];

export type QueryPricesResponses = {
  /**
   * Aggregated prices
   */
  200: PriceResult;
};

export type QueryPricesResponse =
  QueryPricesResponses[keyof QueryPricesResponses];
