// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zDataServiceHealth = z.object({
  status: z.enum(["ok"]),
  service: z.enum(["cs-inv-edit-data"]),
  version: z.string(),
  time: z.iso.datetime(),
});

export const zProviderList = z.object({
  providers: z.array(z.string()),
});

export const zPriceQuery = z.object({
  marketNames: z.array(z.string().min(1)).min(1).max(100),
  currency: z.string().min(1),
  appId: z.int().gte(0).optional(),
});

export const zPriceQuote = z.object({
  source: z.string(),
  marketName: z.string(),
  currency: z.string(),
  amountMinor: z.int().optional(),
  displayPrice: z.string(),
  priceMultiplier: z.number(),
  adjustedAmountMinor: z.int().optional(),
  adjustedDisplayPrice: z.string().optional(),
  listingCount: z.int().optional(),
  url: z.string().optional(),
  observedAt: z.iso.datetime(),
});

export const zPriceItemResult = z.object({
  marketName: z.string(),
  quotes: z.array(zPriceQuote),
});

export const zProviderError = z.object({
  source: z.string(),
  message: z.string(),
});

export const zPriceResult = z.object({
  baselineSource: z.string().optional(),
  currency: z.string(),
  items: z.array(zPriceItemResult),
  listings: z.array(zPriceQuote),
  errors: z.array(zProviderError),
  scannedAt: z.iso.datetime(),
  servedAt: z.iso.datetime().optional(),
  cacheState: z.enum(["fresh", "stale"]).optional(),
});

export const zPriceHistoryResult = z.object({
  marketName: z.string(),
  appId: z.int(),
  currency: z.string(),
  baselineSource: z.string(),
  observations: z.array(zPriceQuote),
});

export const zPriceSearchItem = z.object({
  marketName: z.string(),
  name: z.string(),
  imageUrl: z.string().optional(),
});

export const zPriceSearchResult = z.object({
  items: z.array(zPriceSearchItem),
});

export const zErrorResponse = z.object({
  error: z.string(),
});

/**
 * Service health
 */
export const zGetHealthResponse = zDataServiceHealth;

/**
 * Service readiness
 */
export const zGetReadinessResponse = zDataServiceHealth;

/**
 * Available price providers
 */
export const zListProvidersResponse = zProviderList;

export const zQueryPricesBody = zPriceQuery;

/**
 * Aggregated prices
 */
export const zQueryPricesResponse = zPriceResult;

export const zGetPriceHistoryQuery = z.object({
  marketName: z.string().min(1),
  currency: z.string().min(1),
  appId: z.int().gte(0).optional(),
  source: z.string().optional(),
  from: z.iso.datetime().optional(),
  to: z.iso.datetime().optional(),
  limit: z.int().gte(1).lte(1000).optional().default(200),
});

/**
 * Historical price observations
 */
export const zGetPriceHistoryResponse = zPriceHistoryResult;

export const zSearchPricesQuery = z.object({
  query: z.string().min(1),
  appId: z.int().gte(0).optional(),
  limit: z.int().gte(1).lte(50).optional().default(24),
});

/**
 * Searchable market items
 */
export const zSearchPricesResponse = zPriceSearchResult;
