import type { FeatureFlags, SettingsData } from "@cs-inv-edit/contracts";

const defaultFeatureFlags: FeatureFlags = {
  enableStorageMutations: true,
  enableContainerOpening: false,
  enableInventoryDebug: false,
  showStorageUnitItems: false,
  enableProtocolConsole: false,
  enableTradeups: false,
  enableNameTags: false,
  enableItemDeletion: false,
  enableStatTrakSwap: false,
  enableStrangeParts: false,
  enableItemUse: false,
  enableToolApplication: false,
  enableGifting: false,
  enableTf2Inventory: true,
  enableTf2Store: true,
  enableTf2Loadouts: false,
  enableTf2ItemUse: false,
  enableTf2Tools: false,
  enableTf2Crafting: false,
  enableTf2Tradeups: false,
  enableTf2Unboxing: false,
  enableTf2Customization: false,
  enableDota2Inventory: false,
  enableSteamInventory: true,
  enableStoreRead: false,
  enableStorePurchases: false,
  enableArmoryRedemption: false,
  enablePriceAnalysis: false,
};

export const defaultWasmSettings: SettingsData = {
  backendUrl: window.location.origin,
  validationMode: true,
  sacrificialAccountMode: true,
  featureFlags: defaultFeatureFlags,
  animations: {
    container: "slot-machine",
    tradeUp: "slot-machine",
    armory: "slot-machine",
    terminal: "slot-machine",
  },
  armoryPurchasePacingSeconds: 5,
  storageRetrievalPacingSeconds: 1,
};
