syntax = "proto2";

package cs2item;

option go_package = "cs-inv-edit/backend/internal/proto/generated;cs2pb";

// Source: SteamTracking/GameTracking-CS2 Protobufs/econ_gcmessages.proto, enum EGCItemMsg.
// https://github.com/SteamTracking/GameTracking-CS2/blob/master/Protobufs/econ_gcmessages.proto
enum EGCItemMsg {
  k_EMsgGCBase = 1000;
  k_EMsgGCSetItemPosition = 1001;
  k_EMsgGCCraft = 1002;
  k_EMsgGCCraftResponse = 1003;
  k_EMsgGCDelete = 1004;
  k_EMsgGCNameItem = 1006;
  k_EMsgGCUnlockCrateResponse = 1008;
  k_EMsgGCUseItemRequest = 1025;
  k_EMsgGCRemoveItemName = 1030;
  k_EMsgGCDeliverGift = 1034;
  k_EMsgGCApplyStrangePart = 1073;
  k_EMsgGCSetItemPositions = 1077;
  k_EMsgGCStatTrakSwap = 1088;
  k_EMsgGCItemCustomizationNotification = 1090;
  k_EMsgGCCasketItemAdd = 1092;
  k_EMsgGCCasketItemExtract = 1093;
  k_EMsgGCCasketItemLoadContents = 1094;
  k_EMsgGCOpenCrate = 2534;
}

// Source: SteamTracking/GameTracking-CS2 Protobufs/econ_gcmessages.proto,
// enum EGCItemCustomizationNotification.
// https://github.com/SteamTracking/GameTracking-CS2/blob/master/Protobufs/econ_gcmessages.proto
enum EGCItemCustomizationNotification {
  k_EGCItemCustomizationNotification_UnlockCrate = 1007;
  k_EGCItemCustomizationNotification_XRayItemReveal = 1008;
  k_EGCItemCustomizationNotification_XRayItemClaim = 1009;
  k_EGCItemCustomizationNotification_ExtractSticker = 1054;
  k_EGCItemCustomizationNotification_EncapsulateSticker = 1055;
}

// Source: SteamTracking/GameTracking-CS2 Protobufs/gcsdk_gcmessages.proto,
// enum EGCBaseClientMsg.
// https://github.com/SteamTracking/GameTracking-CS2/blob/master/Protobufs/gcsdk_gcmessages.proto
enum EGCBaseClientMsg {
  k_EMsgGCClientWelcome = 4004;
  k_EMsgGCClientHello = 4006;
  k_EMsgGCClientConnectionStatus = 4009;
  k_EMsgGCClientHelloR2 = 4013;
  k_EMsgGCClientHelloR3 = 4014;
  k_EMsgGCClientHelloR4 = 4015;
}

// Source: SteamTracking/GameTracking-CS2 Protobufs/cstrike15_gcmessages.proto,
// enum ECsgoGCMsg. The file and enum retain legacy CS:GO naming for CS2 GC messages.
// https://github.com/SteamTracking/GameTracking-CS2/blob/master/Protobufs/cstrike15_gcmessages.proto
enum ECsgoGCMsg {
  k_EMsgGCCStrike15_v2_GC2ClientGlobalStats = 9173;
  k_EMsgGCCStrike15_v2_ClientLogonFatalError = 9187;
  k_EMsgGCCStrike15_v2_ClientRedeemMissionReward = 9209;
}

// Source: SteamTracking/GameTracking-CS2 Protobufs/cstrike15_gcmessages.proto.
message CMsgGCCstrike15V2ClientRedeemMissionReward {
  optional uint32 campaign_id = 1;
  optional uint32 redeem_id = 2;
  optional uint32 redeemable_balance = 3;
  optional uint32 expected_cost = 4;
  optional int32 bid_control = 5;
  repeated uint64 volatile_shop = 6;
  optional uint64 souvenir_matchid = 7;
}

message CSOAccountItemPersonalStore {
  optional uint32 generation_time = 1;
  optional uint32 redeemable_balance = 2;
  repeated uint64 items = 3;
}

message CSOAccountXpShopBids {
  optional uint32 campaign_id = 1;
  optional uint32 redeem_id = 2;
  optional uint32 expected_cost = 3;
  optional uint32 generation_time = 4;
}

message CMsgSetItemName {
  optional uint64 subject_item_id = 1;
  optional uint64 tool_item_id = 2;
  optional string name = 3;
}

message CMsgRemoveItemName {
  optional uint64 item_id = 1;
}

message CMsgDeleteItem {
  optional uint64 item_id = 1;
}

message CMsgApplyStatTrakSwap {
  optional uint64 tool_item_id = 1;
  optional uint64 item_1_item_id = 2;
  optional uint64 item_2_item_id = 3;
}

message CMsgApplyStrangePart {
  optional uint64 strange_part_item_id = 1;
  optional uint64 item_item_id = 2;
}

message CMsgUseItem {
  optional uint64 item_id = 1;
  optional fixed64 target_steam_id = 2;
  repeated uint32 gift__potential_targets = 3;
  optional uint32 duel__class_lock = 4;
  optional fixed64 initiator_steam_id = 5;
}

// Source: SteamTracking/GameTracking-CS2 Protobufs/base_gcmessages.proto.
// https://github.com/SteamTracking/GameTracking-CS2/blob/master/Protobufs/base_gcmessages.proto
message CMsgOpenCrate {
  optional uint64 tool_item_id = 1;
  optional uint64 subject_item_id = 2;
  optional bool for_rental = 3;
  optional uint32 points_remaining = 4;
  optional uint32 volatile_limit = 5;
}

message CMsgUseMultipleItems {
  repeated uint64 item_ids = 1;
}

message CMsgApplyToolToItem {
  optional uint64 tool_item_id = 1;
  optional uint64 subject_item_id = 2;
}

message CMsgApplyToolToBaseItem {
  optional uint64 tool_item_id = 1;
  optional uint32 baseitem_def_index = 2;
}

message CMsgGiftItem {
  optional uint64 item_id = 1;
  optional uint32 receiver_account_id = 2;
  optional string gift_message = 3;
}

message CMsgCraftItems {
  optional int32 recipe = 1;
  repeated uint64 item_ids = 2;
}

message CMsgGCItemCustomizationNotification {
  repeated uint64 item_id = 1;
  optional uint32 request = 2;
  repeated uint64 extra_data = 3;
}

message CMsgCasketItem {
  optional uint64 casket_item_id = 1;
  optional uint64 item_item_id = 2;
}

message CMsgSetItemPositions {
  message ItemPosition {
    optional uint32 legacy_item_id = 1;
    optional uint32 position = 2;
    optional uint64 item_id = 3;
  }
  repeated ItemPosition item_positions = 1;
}

message CMsgClientHello {
  optional uint32 version = 1;
  optional uint32 client_session_need = 3;
  optional uint32 client_launcher = 4;
  optional uint32 steam_launcher = 9;
}

message CMsgClientWelcome {
  optional uint32 version = 1;
  optional bytes game_data = 2;
  repeated CMsgSOCacheSubscribed outofdate_subscribed_caches = 3;
}

enum GCConnectionStatus {
  GCConnectionStatus_HAVE_SESSION = 0;
  GCConnectionStatus_GC_GOING_DOWN = 1;
  GCConnectionStatus_NO_SESSION = 2;
  GCConnectionStatus_NO_SESSION_IN_LOGON_QUEUE = 3;
  GCConnectionStatus_NO_STEAM = 4;
}

message CMsgConnectionStatus {
  optional GCConnectionStatus status = 1 [default = GCConnectionStatus_HAVE_SESSION];
  optional uint32 client_session_need = 2;
  optional int32 queue_position = 3;
  optional int32 queue_size = 4;
  optional int32 wait_seconds = 5;
  optional int32 estimated_wait_seconds_remaining = 6;
}

message CMsgGCCStrike15V2ClientLogonFatalError {
  optional uint32 errorcode = 1;
  optional string message = 2;
  optional string country = 3;
}

message CMsgSOIDOwner {
  optional uint32 type = 1;
  optional uint64 id = 2;
}

message CMsgSOCacheSubscribed {
  message SubscribedType {
    optional int32 type_id = 1;
    repeated bytes object_data = 2;
  }

  repeated SubscribedType objects = 2;
  optional uint64 version = 3;
  optional CMsgSOIDOwner owner_soid = 4;
}

message CSOEconItem {
  message Attribute {
    optional uint32 def_index = 1;
    optional uint32 value = 2;
    optional bytes value_bytes = 3;
  }

  optional uint64 id = 1;
  optional uint32 account_id = 2;
  optional uint32 inventory = 3;
  optional uint32 def_index = 4;
  optional uint32 quantity = 5;
  optional uint32 level = 6;
  optional uint32 quality = 7;
  optional uint32 flags = 8;
  optional uint32 origin = 9;
  optional string custom_name = 10;
  optional string custom_desc = 11;
  repeated Attribute attribute = 12;
  optional CSOEconItem interior_item = 13;
  optional bool in_use = 14;
  optional uint32 style = 15;
  optional uint64 original_id = 16;
  optional uint32 rarity = 19;
}
